#! /usr/bin/env python3
"""HOMEINFO Integrated Services File System Daemon."""

from hisfs.config import CONFIG
from hisfs.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
